#!/usr/bin/env python
# coding: utf-8

from boto.sqs import connect_to_region
from boto.exception import SQSError
import simplejson as json
import time
import signal
import sys
import getopt
import os
import random
import string
import logging

# CFG FILE
CFILE='/etc/ec2_collective/ec2-cmaster.json'

def get_config():
    if not os.path.exists(CFILE):
        print CFILE + ' file does not exist'
        sys.exit(1)

    try:
        fp = open(CFILE, 'r')
    except IOError, e:
        print ('Failed to open ' + CFILE + ' (%d) %s \n' % (e.errno, e.strerror))
        sys.exit(1)
    
    try:
        global CFG
        CFG=json.load(fp)
    except (TypeError, ValueError), e:
        print 'Error in configuration file'
        sys.exit(1)

def set_logging(logfile=False):

    log = logging.getLogger()
    logging.getLogger('boto').setLevel(logging.CRITICAL)

    if logfile is not False:

        if os.path.exists(os.path.dirname(logfile)):
            fh = logging.FileHandler(logfile)
            log.addHandler(fh)
        else:
            print >>sys.stderr, 'Log directory does not exist (' + os.path.dirname(logfile) + ')'
            sys.exit(1)

        fh_fmt = logging.Formatter("%(asctime)s %(message)s")
        fh.setFormatter(fh_fmt)
     
    ch  = logging.StreamHandler()
    log.addHandler(ch)
     
    log.setLevel(logging.INFO)  

def usage():
    print >>sys.stderr, '    Usage:'
    print >>sys.stderr, '    ' + sys.argv[0] + ' -c <command>'
    print >>sys.stderr, '    ' + sys.argv[0] + ' -c <command> -l <path to logfile>\t output to console and logfile'
    print >>sys.stderr, '    ' + sys.argv[0] + ' -c <command> -w key=value\tAgent must match this fact'
    print >>sys.stderr, '    ' + sys.argv[0] + ' -c <command> -n key=value\tAgent must NOT match this fact'
    print >>sys.stderr, '    ' + sys.argv[0] + ' -c file://path/to/some/script\tSend file and make agent execute it'
    print >>sys.stderr, '    ' + sys.argv[0] + ' -c s3://bucket/script\tAsk agent to fetch script from s3 and execute'
    print >>sys.stderr, '    ' + sys.argv[0] + ' -c [file://|s3://] -p arg1 arg2\tSend arguments to file:// or s3:// scripts'
    print >>sys.stderr, '    ' + sys.argv[0] + ' -m \tGet a count on responding hosts'
    print >>sys.stderr, '    ' + sys.argv[0] + ' -q <queue name> -c <command>\tOverwrite default SQS queue name'
    print >>sys.stderr, '    ' + sys.argv[0] + ' -c <command> -t <seconds>\tOverwrite default timeout for agent to respond'
    sys.exit(1)

def main():

    global MASTER_EC
    MASTER_EC=0

    # Get configuration
    get_config()

    # Defaults
    mode='ping'
    schedule=time.time()
    cmd=None
    wf=None
    wof=None
    timeout=int(CFG['general']['cmd_timeout'])
    timeout_set = False
    script_param=None
    logfile=False

    try:
        opts, args = getopt.getopt(sys.argv[1:], 'hs:c:w:n:t:p:q:ml:', ['help', 'schedule=', 'command=', 'wf=', 'wc=', 'wof=', 'timeout=', 'script-parameters=', 'sqs-queue=', 'monitor', 'logfile='])
    except getopt.GetoptError, err:
        print >>sys.stderr, str(err) 
        return 1

    for o, a in opts:
        if o in ('-h', '--help'):
            usage()
        elif o in ('-s', '--schedule'):
            if a != 'now':
                # We use the following ts MMDDHHMM
                schedule=a
        elif o in ('-c', '--command'):
            cmd = a
            if 'file://' in cmd:
                mode='script'
                cmd = cmd[7:]
            elif 's3://' in cmd:
                mode='s3'
                cmd = cmd[5:]
            else:
                mode='cli'
        elif o in ('-w', '--wf', '--wc'):
            if wf is not None:
                wf = wf + ',' + a
	    else:
                wf = a
        elif o in ('-n', '--wof'):
            if wof is not None:
                wof = wof + ',' + a
	    else:
                wof = a
        elif o in ('-t', '--timeout'):
            try:
                timeout = int(a)
                timeout_set = True
            except:
                print 'Timeout value is not an integer'
                sys.exit(1)
        elif o in ('-p', '--script-parameters'):
            if mode in ['script', 's3']:
                script_param = a
        elif o in ('-q', '--sqs-queue'):
            CFG['aws']['write_queue'] = str(a)
        elif o in ('-m', '--monitor'):
            mode='count'
        elif o in ('-l', '--logfile'):
            logfile=a

    if mode is None:
        print >>sys.stderr, 'Please provide modetion'
        usage()

    if mode not in ['ping', 'count', 'cli', 'script', 's3' ]:
        print 'Uknown mode: ' + str(a)
        usage()

    set_logging(logfile)

    run (mode, schedule, cmd, wf, wof, timeout, script_param)

# Signal handler
def master_timeout(signum, frame):
    logging.error('Timeout reached - exiting')
    sys.exit(1)

# When timeout happens master_timeout definition executes raising an exception
signal.signal(signal.SIGALRM, master_timeout)

def response_disect(responses, mode, pingcount=0, cmdcount=0 ):

    for response in responses:
        if responses[response]['mode'] == 'ping':
            pingcount += 1
            if mode == 'ping':
                mode_ping_response (responses[response])
        else:
            cmdcount += 1
            mode_cmd_response (responses[response])

    return (pingcount, cmdcount)

def mode_ping_response (response):
    hostname = str(response['hostname'])
    output = str(response['output'])

    response_time = round( (time.time() - float(output)) * 1000, 2 )
    response_str = hostname + ' time=' + str(response_time) + ' ms'

    logging.info(response_str)

def mode_cmd_response (response):

    global MASTER_EC

    hostname = str(response['hostname'])
    output = str(response['output'])
    rc = str(response['rc'])

    if int(rc) != 0:
        MASTER_EC = int(rc)

    response_str = '>>>>>> ' + hostname + ' exit code: ('+str(rc)+'):\n' +  str(output)

    logging.info(response_str)

def receive_responses (read_queue, org_ids, mode, timeout ):

    if mode in [ 'ping','count' ]:
        timeout=CFG['general']['ping_timeout']

    ptimeout=CFG['general']['ping_timeout']

    total_responses = {}
    old_msgs = {}
    agent_msgs = {}
    pingcount=0
    cmdcount=0

    start_time=int(time.time())
    while ( True ):
        responses, old_msgs = pull_msgs (read_queue, org_ids, old_msgs)
        if len(responses) > 0:
            (pingcount, cmdcount) = response_disect(responses, mode, pingcount, cmdcount )

        if ((int(time.time()) - start_time) >= ptimeout and pingcount == cmdcount):
            logging.debug('Ping timeout reached (' + str(ptimeout) + ') and got response from all')
            break

        if ((int(time.time()) - start_time) >= timeout):
            logging.debug('cmd timeout reached ' + str(timeout) )
            break

    return (pingcount, cmdcount)

def pull_msgs (read_queue, org_ids, old_msgs ):

    response = None
    responses = {}

    # Receive at least 1 message be fore continuing 
    rmsgs = read_queue.get_messages(num_messages=10, visibility_timeout=2)

    # For each message we check for duplicate, and if it is a response to our org message
    for rmsg in rmsgs:

        # PUT FIRST Avoid duplicates 
        if rmsg.id in old_msgs:
            continue
        else:
            old_msgs[rmsg.id] = rmsg.id

        response=json.loads(rmsg.get_body())
        msg_id = str(response['msg_id'])

        # Is it a response to our original request
        if msg_id not in org_ids:
            # Dont handle it again
            old_msgs[rmsg.id] = rmsg.id
            continue

        responses[msg_id] = response

        # We're done with the message - delete it
        if not read_queue.delete_message(rmsg):
            logging.error('Failed to delete reponse message')

    # Retrun all responses
    return (responses, old_msgs)

def delete_org_message (write_queue, msg_ids):

    signal.alarm(CFG['general']['clean_timeout'])

    while ( True ):
        msg_ids = pull_org_msgs (write_queue, msg_ids)
        if len(msg_ids) == 0:
            break

    signal.alarm(0)

def pull_org_msgs(write_queue, msg_ids):

    # Pick up written message and delete it
    wmsgs = write_queue.get_messages(num_messages=10, visibility_timeout=2)
    
    for wmsg in wmsgs:
    
        if wmsg.id in msg_ids:
            if not write_queue.delete_message(wmsg):
                logging.error('Failed to delete original command message')
                continue
            else:
                del msg_ids[wmsg.id]
        else:
            continue

    return msg_ids

def id_generator(size=10, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for x in range(size))

def dict_to_sqs_obj(message, write_queue):

    message_json=json.dumps(message)

    if len(message) >= 65536:
        logging.error ('Message is too big to put on SQS')
        sys.exit(1)

    try:
        message = write_queue.new_message(message_json)
    except:
        logging.error('Failed to create message object - check queue name')
        sys.exit(1)

    return message

def write_msg (write_queue, dict_message):

    message=dict_to_sqs_obj(dict_message, write_queue)
    org_ids={}

    written=False
    for i in range(0, 3):
        try:
            org = write_queue.write(message)
        except:
            logging.error('Failed to write command message')
            sys.exit(1)

        if org.id is None:
            logging.error('Failed to write 1 command message')
        else:
            written=True
            org_ids[org.id] = org.id

    if written is True:
        return org_ids
    else:
        logging.error('Failed to write any command messages')
        sys.exit(1)

def inhale_script (script_file):
    if not os.path.exists(script_file):
        logging.error(str(script_file) + ' file does not exist')
        sys.exit(1)

    f = open(script_file, 'r')

    return f.read()

def run(mode, schedule, cmd, wf, wof, timeout, script_param):
    global MASTER_EC

    payload = None

    if mode == 'script':
        payload = inhale_script(cmd)
        cmd = os.path.basename(cmd)

    responses={}
    ping_responses={}
    org_ids={}
    discovered=None

    # Connect with key, secret and region
    try:
        conn = connect_to_region(CFG['aws']['region'])
    except:
        logging.error('Could not connect to SQS - check your authentication')
        sys.exit(1)

    write_queue = conn.get_queue(CFG['aws']['write_queue'])
    read_queue = conn.get_queue(CFG['aws']['read_queue'])

    if write_queue is None or read_queue is None:
        logging.error('Unable to get queue by name')
        sys.exit(1)

    # Construct message, send and receive
    message={'mode':mode,'schedule':schedule, 'cmd':cmd, 'ts':time.time(), 'wf':wf, 'wof':wof, 'batch_msg_id':id_generator()}
    org_ids.update (write_msg(write_queue, message))
    (pingcount, cmdcount) = receive_responses (read_queue, org_ids, mode, timeout)

    # 15 second initial timeout  
    if mode == 'count':
	logging.info(str(pingcount))

    # Delete original messags
    delete_org_message (write_queue, org_ids)

    if mode in ['cli', 'script', 's3'] and pingcount != cmdcount:
        for hostname in ping_responses.keys():
            if not hostname in responses:
                logging.info('Timeout in response from: ' + hostname)

        # If some of the expected servers did not answer we exit 1
        MASTER_EC=1

    if len(responses) == 0:
        MASTER_EC=1

    if mode is not 'count':
        logging.info('Got response from ' + str(cmdcount) + ' out of ' + str(pingcount) + ' (discovered)' + ' - exit code ('+str(MASTER_EC)+')')
        sys.exit(MASTER_EC)

if __name__ == "__main__":
    sys.exit(main())
