#!/usr/bin/env python
# coding: utf-8

import sys

# CHANGE THESE SETTINGS

# Number of servers in farm
SERVERS=50

# Commands you issue pr day
COMMANDS_PER_DAY=100

# Poll interval from config file
SQS_POLL_INTERVAL=2

# Attention poll inteval from config file
SQS_ATT_POLL_INTERVAL=0.1

# Attention time
SQS_ATT_POLL_PERIOD=60

# Days in a month
DAYS_IN_MONTH=31

def calculate ( free_tier_req, dollar_pr_request ):
    poll_request_pr_day = ( (60 / SQS_POLL_INTERVAL) * 60 * SERVERS * 24 )
    att_poll_requests_pr_day = ( COMMANDS_PER_DAY * ( SQS_ATT_POLL_PERIOD / SQS_ATT_POLL_INTERVAL ) )
    total_request_pr_month = ( (att_poll_requests_pr_day  + poll_request_pr_day) * DAYS_IN_MONTH )
    price_pr_month = ( (total_request_pr_month - free_tier_req) * dollar_pr_request )
    print 'SQS check request amount to $' + str(poll_request_pr_day * DAYS_IN_MONTH * dollar_pr_request) 
    print 'SQS attention check request amount to $' + str(att_poll_requests_pr_day * DAYS_IN_MONTH * dollar_pr_request)
    print 'SQS price pr month in $' + str(price_pr_month)

def main ():
    free_tier_req=100000
    dollar_pr_request=0.000001

    calculate(free_tier_req, dollar_pr_request)

if __name__ == "__main__":
    sys.exit(main())
